### ISSUE TITLE
Error, when using proxy

### ISSUE THREAD

**Issue by vinaybedre** [phulas/x-ray-nightmare#1]
Hi,

I used below code for testing.

```
var Xray = require('x-ray');
var NightmareElectron = require('x-ray-nightmare');
var phantom = require('x-ray-phantom');

var nightmareOptions = {
  switches: {
    'proxy-server': 'http://proxy:8080', //Proxy here
    'ignore-certificate-errors': true
  }
};

var nightmareDriver = NightmareElectron(nightmareOptions);

var x = Xray({
    filters: {
      fixURL: function (value) {
        return value;
      }
    }
  })
  .driver(nightmareDriver);


// x.driver('')
x('https://www.amazon.in/s/ref?rh=n%3A976419031%2Cn%3A%21976420031%2Cn%3A1389401031%2Cn%3A1389432031&ie=UTF8&qid=1437323774&page=1', 'li[id^=result_][class!=s-hidden-sponsored-item]', [{
    title: 'h2.a-size-base',
    image: 'img.s-access-image@src',
    targetURL: 'a.a-link-normal@href | fixURL'
  }]).paginate('a#pagnNextLink@href')
  .limit(90)
  .write('results.json');
```

As soon I run the script, after first page, it errors out with following error

> events.js:141
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error
>     at EventEmitter.<anonymous> (/Applications/MAMP/htdocs/nodejs-be/node_modules/x-ray-nightmare/index.js:46:33)
>     at emitMany (events.js:113:20)
>     at EventEmitter.emit (events.js:182:7)
>     at ChildProcess.<anonymous> (/Applications/MAMP/htdocs/nodejs-be/node_modules/x-ray-nightmare/node_modules/nightmare/lib/ipc.js:49:10)
>     at emitTwo (events.js:87:13)
>     at ChildProcess.emit (events.js:172:7)
>     at internal/child_process.js:696:12
>     at nextTickCallbackWith0Args (node.js:420:9)
>     at process._tickCallback (node.js:349:13)

**Comment by mashaalmemon** [comment]
Hi @vinaybedre 

I don't personally use a proxy in my environment but I'm extrapolating that some portion of the page you were trying to hit failed to load as a result of using your proxy. I've found in my own use of nightmare that the 'did-fail-load' event of nightmare is not necessary an event that warrants notification or will prevent a crawl from completing successfully. As such in the latest version 0.1.13, an error is no longer thrown for the 'did-fail-load' event. Get the latest version and see if it solved your problem.
