### ISSUE TITLE
Does this expose other nightmare functionality such as `wait`, `click` etc? 

### ISSUE THREAD

**Issue by geertbrit** [phulas/x-ray-nightmare#3]
as per title. Thanks

**Comment by buywithkyosk** [comment]
Yes through the `customFunction`.

Take a look at the [API section of the docs](https://github.com/phulas/x-ray-nightmare#api)

In a nutshell:

- If a `customFunction` is specified, x-ray will pass control to the `customFunction`. 
- **The nightmare object is passed into the `customFunction` as an object. This is where you may perform intended browser action via nightmare functionality ('wait', 'click', etc.).**
- You'll notice that the custom function should be a [generator function](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/function*v). You'll need to yield control to the nightmare object as per generator semantics. But the generator is executed using [co](https://www.npmjs.com/package/co) so yields will be handled seamlessly for you. 
- Once the `customFunction` is done executing, the current html is passed back to x-ray for processing.

**Comment by mashaalmemon** [comment]
Yes through the `customFunction`.

Take a look at the [API section of the docs](https://github.com/phulas/x-ray-nightmare#api)

In a nutshell:

- If a `customFunction` is specified, x-ray will pass control to the `customFunction`. 
- **The nightmare object is passed into the `customFunction` as an object. This is where you may perform intended browser action via nightmare functionality ('wait', 'click', etc.).**
- You'll notice that the custom function should be a [generator function](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/function*v). You'll need to yield control to the nightmare object as per generator semantics. But the generator is executed using [co](https://www.npmjs.com/package/co) so yields will be handled seamlessly for you. 
- Once the `customFunction` is done executing, the current html is passed back to x-ray for processing.

**Comment by geertbrit** [comment]
Cheers
