### ISSUE TITLE
Header support

### ISSUE THREAD

**Issue by roccomuso** [phulas/x-ray-nightmare#5]
It would be useful to support headers.

**Comment by mashaalmemon** [comment]
@roccomuso I assume you mean the ability to specify headers along with the url you are visiting?

If you implement using the custom function (see x-ray-nightmare [readme](https://github.com/phulas/x-ray-nightmare/blob/master/README.md)) , you can pass through headers to the page. Read the nightmarejs 'goto' function signature [description](https://github.com/segmentio/nightmare#interact-with-the-page) in nightmarejs documentation.
